### ISSUE TITLE
NM should spawn after so many waterings

### ISSUE THREAD

**Issue by Jaampayih** [TabulaRasaXI/TabulaRasa#100]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

base

## Steps to reproduce

Trade waters to ??? in Tahrongi Canyon and should spawn NM after so many waterings
https://ffxiclopedia.fandom.com/wiki/Yara_Ma_Yha_Who?oldid=551786

NM won't spawn after using stack of water.  When looking at https://github.com/TabulaRasaXI/TabulaRasa/blob/staging/sql/nm_spawn_points.sql I don't see him in there as having a spawn location.

 YARA_MA_YHA_WHO   = 17256900

## Expected behavior

NM should spawn after so many waterings

**Comment by The-Aerec** [comment]
Hi this mob isn't controlled by something in NM_spawn_points:

Its controlled via:

```lua

-----------------------------------
-- Area: Tahrongi Canyon
--  NPC: qm2 (???)
-- Note: Used to spawn Yara Ma Yha Who
-- !pos 271 0.001 -334 117
-----------------------------------
local ID = require("scripts/zones/Tahrongi_Canyon/IDs")
require("scripts/globals/npc_util")
-----------------------------------
local entity = {}

entity.onTrade = function(player, npc, trade)
    -- Trade Distilled water to Spawn Yara Ma Yha Who
    if npcUtil.tradeHas(trade, 4509) and not GetMobByID(ID.mob.YARA_MA_YHA_WHO):isSpawned() then
        if os.time() > npc:getLocalVar("tradeCooldown") then
            local trades = npc:getLocalVar("trades")

            if trades >= 3 and math.random(100) <= 50 then
                player:messageSpecial(ID.text.REPULSIVE_CREATURE_EMERGES)
                SpawnMob(ID.mob.YARA_MA_YHA_WHO):updateClaim(player)
                npc:setLocalVar("trades", 0)
            else
                player:messageSpecial(ID.text.SPROUT_LOOKING_BETTER)
                npc:setLocalVar("trades", trades + 1)
            end

            player:confirmTrade()
            npc:setLocalVar("tradeCooldown", os.time() + 3000) -- 50 minute until next trade
        else
            player:messageSpecial(ID.text.SPROUT_DOES_NOT_NEED_WATER)
        end
    else
        player:messageSpecial(ID.text.NOTHING_HAPPENS)
    end
end

entity.onTrigger = function(player, npc)
    if os.time() > npc:getLocalVar("tradeCooldown") then
        player:messageSpecial(ID.text.SPROUT_LOOKS_WITHERED)
    else
        player:messageSpecial(ID.text.SPROUT_LOOKING_BETTER)
    end
end

entity.onEventUpdate = function(player, csid, option)
end

entity.onEventFinish = function(player, csid, option)
end

return entity

```

Can you provide details on how many waters you traded / the messages you were getting?

**Comment by Jaampayih** [comment]
I trade a 1 stack of 12 water and it says the sprout is looking better every time

**Comment by The-Aerec** [comment]
Did you trade 1 at a time or the entire stack at once?

**Comment by Jaampayih** [comment]
1 every 50 mins or alil over 50 mins

**Comment by austinclprojects** [comment]
![image](https://user-images.githubusercontent.com/73414815/188523897-6dd55fad-d506-452d-a605-249b20a00bba.png)

Seems to be working, closing for now.
