### ISSUE TITLE
WS Accuracy

### ISSUE THREAD

**Issue by JDFlashffxi** [TabulaRasaXI/TabulaRasa#105]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Describe the feature

First hit of WS have a +100acc bonus, this was part of the orginial design to offset the 100% acc of elemental WS for skillchaining purposes, it was later confirmed by devs in a QnA that has been translated to english on BG Forums in the link ill provide, it was confirmed when asking about extending the acc bonus to multi hit ws after the first hit.

https://www.bluegartr.com/threads/112776-Dev-Tracker-Findings-Posts-(NO-DISCUSSION)?p=6633828&highlight=accuracy#post6633828
![WS acc](https://user-images.githubusercontent.com/48188921/178539737-bad8ebbf-062d-4a41-ae55-0a87eb3c69a0.png)

**Comment by 0phie** [comment]
Thanks for the quality bug report! This will be fixed once TR merges https://github.com/AirSkyBoat/AirSkyBoat/pull/115.
