### ISSUE TITLE
Labyrinth Lizards in Crawlers' Nest using Iceball instead of Fireball

### ISSUE THREAD

**Issue by Shiftie-Bassturd** [TabulaRasaXI/TabulaRasa#112]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Labyrinth Lizards in Crawlers' Nest are using snowball.

![snowball](https://user-images.githubusercontent.com/109208330/178696962-df6b353a-dade-4f07-9a5b-bb440bb2d620.png)

## Expected behavior

Labyrinth Lizards in Crawlers' Nest should be using fireball. Ice based lizards in Pso'Xja are the only regular mob that uses iceball.

![snowballwiki](https://user-images.githubusercontent.com/109208330/178696966-d8b4f422-0fbc-4c7b-b91d-974a81241810.png)

**Comment by austinclprojects** [comment]
https://github.com/TabulaRasaXI/TabulaRasa/pull/240
