### ISSUE TITLE
OOE Item: Orcish Armor Plate

### ISSUE THREAD

**Issue by Shiftie-Bassturd** [TabulaRasaXI/TabulaRasa#115]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Orcish Armor Plate drops from the following mobs:

Fort_Ghelsba (141)
Orcish Stonechucker

Yughott_Grotto (142)
Orcish Grunt 
Orcish Neckchopper
Orcish Stonechucker
Orcish Cursemaker 
Orcish Fighter
Orcish Serjeant 

King Ranperres Tomb (190)
Goblin Tinkerer
Goblin Ambusher
Goblin Butcher 
Goblin Mugger 
Goblin Gambler
Goblin Leecher 

## Expected behavior

Orcish Armor Plate introduced in 2009.

![orcisharmorplatehistory](https://user-images.githubusercontent.com/109208330/178723973-17ea5b13-d90c-4e61-8cd3-870efa5cfc12.png)

**Comment by austinclprojects** [comment]
https://github.com/TabulaRasaXI/TabulaRasa/pull/157
