### ISSUE TITLE
OOE Item: Quadav Backscale

### ISSUE THREAD

**Issue by Shiftie-Bassturd** [TabulaRasaXI/TabulaRasa#116]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Quadav Backscale drops from the following mobs:

Palborough Mines (143)
Greater Quadav 
Onyx Quadav 
Veteran Quadav
Brass Quadav 
Copper Quadav
Old Quadav

Dangruf_Wadi (191)
Goblin Ambusher
Goblin Butcher

There is also an Unknown - Unknown that drops the Backscale. It appears that this should be -- ZoneID: 191 - Goblin Mugger. The loot table matches what the Wadi Goblin Mugger should drop.

-- ZoneID: Unknown - Unknown
INSERT INTO `mob_droplist` VALUES (1119,0,0,1000,750,@UNCOMMON);  -- Silver Beastcoin (Uncommon, 10%)
INSERT INTO `mob_droplist` VALUES (1119,0,0,1000,2758,@UNCOMMON); -- Quadav Backscale (Uncommon, 10%)
INSERT INTO `mob_droplist` VALUES (1119,0,0,1000,510,@RARE);      -- Goblin Armor (Rare, 5%)
INSERT INTO `mob_droplist` VALUES (1119,0,0,1000,511,@RARE);      -- Goblin Mask (Rare, 5%)
INSERT INTO `mob_droplist` VALUES (1119,0,0,1000,12449,@VRARE);   -- Brass Cap (Very Rare, 1%)
INSERT INTO `mob_droplist` VALUES (1119,0,0,1000,12705,@VRARE);   -- Brass Mittens (Very Rare, 1%)
INSERT INTO `mob_droplist` VALUES (1119,0,0,1000,12833,@VRARE);   -- Brass Subligar (Very Rare, 1%)
INSERT INTO `mob_droplist` VALUES (1119,0,0,1000,12961,@VRARE);   -- Brass Leggings (Very Rare, 1%)
INSERT INTO `mob_droplist` VALUES (1119,2,0,1000,750,0);          -- Silver Beastcoin (Steal)

![wadimugger](https://user-images.githubusercontent.com/109208330/178748433-57430903-451f-4c1c-990f-df878aad3f5f.png)

## Expected behavior

Quadav Backscale introduced in 2009.

![quadav backscale](https://user-images.githubusercontent.com/109208330/178725858-861eca5d-47a3-4422-ab69-27043d84263f.png)

**Comment by austinclprojects** [comment]
https://github.com/TabulaRasaXI/TabulaRasa/pull/157
