### ISSUE TITLE
OOE Item: Yagudo Caulk

### ISSUE THREAD

**Issue by Shiftie-Bassturd** [TabulaRasaXI/TabulaRasa#117]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Yagudo Caulk drops from the following mobs:

Giddeus (145)
Yagudo Mendicant
Yagudo Piper
Yagudo Persecutor
Yagudo Priest
Yagudo Theologist
Yagudo Votary

Inner Horutoto Ruins (192)
Goblin Mugger
Goblin Leecher

West_Sarutabaruta_[S] (95)
Yagudo Persecutor(Incorrectly shares droplist with Persecutor from Giddeus. See image below).

-- ZoneID:  95 - Yagudo Persecutor
-- ZoneID: 145 - Yagudo Persecutor
INSERT INTO `mob_droplist` VALUES (2741,0,0,1000,498,@VCOMMON); -- Yagudo Bead Necklace (Very Common, 24%)
INSERT INTO `mob_droplist` VALUES (2741,0,0,1000,750,@COMMON);  -- Silver Beastcoin (Common, 15%)
INSERT INTO `mob_droplist` VALUES (2741,0,0,1000,2759,80);      -- Block Of Yagudo Caulk (8.0%)
INSERT INTO `mob_droplist` VALUES (2741,0,0,1000,12456,@VRARE); -- Hachimaki (Very Rare, 1%)
INSERT INTO `mob_droplist` VALUES (2741,0,0,1000,12712,@VRARE); -- Tekko (Very Rare, 1%)
INSERT INTO `mob_droplist` VALUES (2741,0,0,1000,12840,@VRARE); -- Sitabaki (Very Rare, 1%)
INSERT INTO `mob_droplist` VALUES (2741,0,0,1000,12968,@VRARE); -- Kyahan (Very Rare, 1%)
INSERT INTO `mob_droplist` VALUES (2741,2,0,1000,656,0);        -- Beastcoin (Steal)

![yagpersdroplist](https://user-images.githubusercontent.com/109208330/178735846-1ec4826f-c3d5-4113-a7b0-557330d36e5c.png)

## Expected behavior

Yagudo Caulk introduced in 2009.

![yagudocaulkhistory](https://user-images.githubusercontent.com/109208330/178737597-94b9e5a2-8150-4b51-a77d-87cee7f7e6db.png)

**Comment by austinclprojects** [comment]
https://github.com/TabulaRasaXI/TabulaRasa/pull/157
