### ISSUE TITLE
🐛Wight intimated by Aquans

### ISSUE THREAD

**Issue by MoonSnow** [TabulaRasaXI/TabulaRasa#119]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

 Using a clipper as a pet (BST subbed), I was fighting a undead at Qufim near Delkfutt's tower. The Wight was intimidated by the Clipper's presence. Pretty sure undead aren't intimated by Aquans.

## Expected behavior

Shouldn't be intimated at all.

**Comment by 0phie** [comment]
This is due to aquans being PLDs primarily, thus they naturally have a undead killer effect.
