### ISSUE TITLE
Sword Madrigal - Bard

### ISSUE THREAD

**Issue by jlroush24** [TabulaRasaXI/TabulaRasa#121]
At level 43 BARD, and near capped Skill, Sword Madrigal is capped out at 5 Accuracy Bonus which should be much higher.. I saw this on wings at one time, I'd assume its the same deal here.  +5 ACC is the same bonus as a level 12 Bard.

Accuracy bonus is a function of combined Singing and Instrument Skill by the Bard. The natural cap of the Accuracy bonus is +45.[[1]](https://ffxiclopedia.fandom.com/wiki/Sword_Madrigal#cite_note-1)
Stacks with other [Madrigal](https://ffxiclopedia.fandom.com/wiki/Madrigal) effects.

Equipment that gives "Madrigal +" or "All Songs +" increases the total Accuracy bonus and duration of the song by 10% for every +1 granted.

**Comment by 0phie** [comment]
Fixed in https://github.com/AirSkyBoat/AirSkyBoat/pull/119
