### ISSUE TITLE
🐛 Broken fishing messages in Mhaura->Selbina ferry with pirates

### ISSUE THREAD

**Issue by anilanar** [TabulaRasaXI/TabulaRasa#125]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

1. Use the latest FFXI client (didn't test others).
2. Try to fish in Mhaura->Selbina ferry with pirates. I used Yew fishing rod + crayfish balls.

![2022-07-14-13-52-32](https://user-images.githubusercontent.com/753736/179008878-a2c28cbb-f7f7-4c25-85fe-3a519b41bdae.png)

**Comment by anilanar** [comment]
I can confirm that this still happens on 24.07.2022.

**Comment by Amphiptera** [comment]
![image](https://user-images.githubusercontent.com/118571991/202808205-36a01971-f187-4b2f-af26-119532ed656b.png)

Similar issue, 11/18/2022 - In Windurst Woods (can't catch monsters there...)

**Comment by bran-van-d** [comment]
This is occurs when a user does not have a properly updated XI client.
