### ISSUE TITLE
🐛 Rage system issues

### ISSUE THREAD

**Issue by Simseru** [TabulaRasaXI/TabulaRasa#126]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce
The current NM rage system is wiping as soon as a mob losses enmity. 

We fought Simurgh and weren't sure if he raged but we zoned to heal up and recover and then went back out and zoned and killed him.

Fought KA and as soon as he raged(nukes started healing him is what we identified as rage activating) we all zoned and rage immediately dropped after zoning.

Recommend rage persisting until mobs are regen'd to 100%

![Rage](https://user-images.githubusercontent.com/59345270/179156355-346968d3-d747-47be-99ef-c135f73f88b2.png)
You can see where Ramuh's judgement bolt healed him. We were still dealing alright dmg so the rage doesn't seem to make NMs super tanky. We did start missing noticeably more so the rage seems to add some evasion but I would expect more. He hit the DRG for 160 with the rage active and was hitting us for 100-140 with out the rage.

Recommend making the rage much more potent.

Was not paying attention to the duration of the fight to see the fight time for the rage trigger.

**Comment by austinclprojects** [comment]
https://ffxiclopedia.fandom.com/wiki/Talk:Rage

Expected behavior
