### ISSUE TITLE
🐛 Digging: Missing Allows Instant Redig

### ISSUE THREAD

**Issue by MeyiLekoh** [TabulaRasaXI/TabulaRasa#129]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

When digging, I noticed if I missed a dig attempt, I was able to dig again immediately after. I don't know if this is intentional or not, so I am submitting a ticket just in case. Previous servers had the timer last the same duration regardless of whether an item was obtained or not.

I'm attaching screenshots that show when I obtained an item, I had to wait the entire 11 seconds for my next digging attempt. But if I missed the dig, I was able to dig again much sooner than 11 seconds (about 5 seconds according to the time stamp, most of that waiting for the dig animation to complete). I am currently Rank 2/Recruit.

## Steps to reproduce

1. Dig until you get the message, "You dig and you dig, but find nothing."
2. Dig immediately after animation is over.

## Expected behavior

I assume same time between each dig, regardless of whether item was obtained or not.

![Instant Redig](https://user-images.githubusercontent.com/47701928/179342051-53dd9222-ad0b-4be8-93ef-cf4ed40b4c9e.png)

![Instant Redig2](https://user-images.githubusercontent.com/47701928/179342052-3a15c38f-fdaf-426e-b8b0-e62ec07430d2.png)

**Comment by Simseru** [comment]
I'll chime in and say I have seen the same thing happen as well but it didnt happen consistently for me after every miss text, just some.

**Comment by soapytoast** [comment]
I believe this should have been resolved in a recent update to delays in digging.
