### ISSUE TITLE
Mythril swords are set at 90 skill to catch

### ISSUE THREAD

**Issue by twelvedudes** [TabulaRasaXI/TabulaRasa#13]
INSERT INTO `fishing_fish` VALUES (16537,'Mythril Sword',90,15,13,2,1,1,10,0,0,255,255,0,0,0,0,0,0,0,1,1,60,0,'',0,0,0,0);

several guides and wikis say you can catch them much earlier in era 

(https://ffxi.allakhazam.com/db/item.html?fitem=1700

"I caught quite a few of these while I was skill up fishing in Qufim on the cliff to the left of the Jeuno entrance. I went from 54-65 fishing there, I need to fish more been busy with Alchemy lately."
"I also caught one of these while fishing in Batallia Downs as a lvl 18 fisher + fishing gear. I was fishing with a Halcyon Rod and Minnow lure. That being said, I fished for 3 game days and only got one.")

**Comment by bran-van-d** [comment]
Closing this as there isn't any data I was able to find beyond the Allakhazam thread. It's also a pretty niche issue -- if we it comes up again we can take a look!
