### ISSUE TITLE
🐛 Elemental Seal Weak / Does Nothing

### ISSUE THREAD

**Issue by Simseru** [TabulaRasaXI/TabulaRasa#136]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce
Used multiple Ele Seal + Nuke and have been partially resisted every time. Looked at the damage_spell.lua it looks like there is nothing coded for Ele Seal to provide additional macc on nukes, numerous other abilities /effects are coded.

Not sure about enfeebles as that uses different lua.

**Comment by Simseru** [comment]
Ele Seal > Thunder on a VT leach 3 levels higher than me still got half resisted.
I don't think ele seal >> nuke should be resisted in a scenario like that. 
![EleSeal](https://user-images.githubusercontent.com/59345270/179861189-e2c52832-bd7f-4214-a80b-66ccb250c810.PNG)
![EleSeal2](https://user-images.githubusercontent.com/59345270/179861203-d4f78128-8827-4577-a263-94e509d97031.PNG)

![Stats](https://user-images.githubusercontent.com/59345270/179861339-99e76a37-37d9-475e-ba07-35bb045c78c9.PNG)
![Skills](https://user-images.githubusercontent.com/59345270/179861350-b2225c9a-958b-42d1-9a84-7d041a83b22a.PNG)

I am /nin because i have 31INT as /nin and 32INT as /rdm but /NIN allows a second wand for overall more total INT.

**Comment by Simseru** [comment]
10 mins later, heres another ele seal resist, this time on a decent chalenge.
![EleSeal1A](https://user-images.githubusercontent.com/59345270/179862646-e35e5058-8d07-4972-8c55-551e14e62218.PNG)
![Eleseal1B](https://user-images.githubusercontent.com/59345270/179862651-12c01f09-c5cf-487e-aa8e-b9c32368cac2.PNG)

**Comment by twelvedudes** [comment]
yeah all of the magic was fine then whatever that "fix" was made it so it almost always resists
