### ISSUE TITLE
🐛 summoner avatars are not attacking as intended

### ISSUE THREAD

**Issue by twelvedudes** [TabulaRasaXI/TabulaRasa#140]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x ] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [ x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

summoners avatars should automatically attack mobs that attack them, this is not the case

## Steps to reproduce

summon an avatar and be attacked

## Expected behavior

avatar automatically attacks mobs that attack the summoner

**Comment by soapytoast** [comment]
https://github.com/TabulaRasaXI/TabulaRasa/pull/181/commits/04bcfb1f099ff3f051fffef9a3843d854cc5677d
