### ISSUE TITLE
🐛 Magic Burst Elemental Mismatch

### ISSUE THREAD

**Issue by Simseru** [TabulaRasaXI/TabulaRasa#144]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce
When in a party when the Reverberation SC was made which should MB with water, I was having to MB with thunder instead.
Induration is supposed to be blizzard, but stone was MBing instead.

**Comment by MeyiLekoh** [comment]
Distortion also bursts with stone and allegedly dark. Haven't seen dark burst on it yet, but I can confirm stone does. (Distortion should be ice/water)

**Comment by austinclprojects** [comment]
![image](https://user-images.githubusercontent.com/73414815/180886263-efe9de0c-db3c-48b4-9ea1-3ca4c54cb831.png)

Working for me, mind provided a screenshot?

**Comment by Simseru** [comment]
This was fixed a few days ago in the recent patch.

The spells were tagged with the incorrect element.

`-- Stone, Water, Blizzard, Thunder, Aero 1-4 and their respective -ga spells' elements corrected.`
