### ISSUE TITLE
Camouflage

### ISSUE THREAD

**Issue by Blackwingedicey** [TabulaRasaXI/TabulaRasa#145]
Was messing around in ordells caves, used Camouflage, had 1200 TP engaged a beetle and used Piercing arrow, Camouflage stayed up until i fired a normal /ra <t> arrow.

~Icey

**Comment by austinclprojects** [comment]
Yea this seems like a bug, opened an issue on the LSB board.

https://github.com/LandSandBoat/server/issues/2401

**Comment by austinclprojects** [comment]
https://github.com/LandSandBoat/server/pull/2407
