### ISSUE TITLE
🐛 rage does not work on sheep jug pets. 

### ISSUE THREAD

**Issue by twelvedudes** [TabulaRasaXI/TabulaRasa#147]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

hopefully all pets moves are not broken. here is an example of a HQ sheep pet not changing damage after rage. after using the skill with check param you can see DEF goes down by 1 point and ATK goes up by 1 point

![image](https://user-images.githubusercontent.com/108678300/180351962-cebeb6d4-a1c8-472e-b974-d1993821d363.png)

![image](https://user-images.githubusercontent.com/108678300/180353504-6f405d5f-2264-4c59-a587-5d2c5490e44b.png)

he

## Steps to reproduce

none

## Expected behavior

sheep jugs pets do mroe damage

**Comment by neosatus** [comment]
Issue found, PR made for ASB. Ticket can be closed pending merge. @soapytoast
