### ISSUE TITLE
🐛 Elemental fully resets when weather changes to another weather of same element

### ISSUE THREAD

**Issue by yuzumika** [TabulaRasaXI/TabulaRasa#153]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

1) Aggro an elemental (Ice Elemental in Beaucedine Glacier)
2) Weather changes to another weather of the same element (Ice --> Double ice)
3) Elemental resets to spawn position with full HP.

## Expected behavior

Elemental should not react when the weather changes after being claimed.

**Comment by neosatus** [comment]
This should be fixed in Tuesday's patch. @soapytoast
