### ISSUE TITLE
🐛 Sturmtiger DRG AF2

### ISSUE THREAD

**Issue by Simseru** [TabulaRasaXI/TabulaRasa#154]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce
Monster was way too weak.
lvl 36 bounty hunter I TP'd on before fight. About 1000 DMG
![Bounty](https://user-images.githubusercontent.com/59345270/180654282-4c24c669-2cd8-4c75-82bd-0b47a89745e9.PNG)

Sturmtiger for AF2. 979DMG(with  some overkill from the VB)
![Sturm](https://user-images.githubusercontent.com/59345270/180654327-0e3d2248-5143-4437-94ad-cc014bfa1d2d.PNG)

## Expected behavior
`Can be solo as DRG70/PLD35. Start with 100%TP. Penta Thrust, Sentinel, then Jump x 2, 2-hour, Jump x 2 again and 1 more Penta Thrust. Then let auto hit finish it. 1 Healing Breath was triggered. The tabby die before i got the 3rd Penta. - Nethomas@Lakshmi`

`This was a fairly easy solo for my 61thf/nin....was a dual box for my wifes 50 drg and only used her to pop the tiger, i think he hit her twice and she was out cold, no fancy gear, just bloody bolts and i used a lot of sleep bolts so i could easily keep shadows up, at one point i chucked the wrong bolts and he took me into low yellow with one hit, a deep breath and started chucking bloody bolts again, fight took maybe 8-9 minutes, walked away with 90% health, wife had field manual reraise up...not a recoed breaker by any means, but really a easy fight...at least as long as knife and markmanship is capped, i only used squid sushi [GreyDragon/Quetzlcotl]`

`Rough duo by 75 DRG/WHM and 53 DRG/WAR. The first try we wiped because I (75 DRG) couldn't get Poisona off. The second try it got close but my wyvern's Healing Breath III kept us both alive. This tiger hits *really* hard to a player with 249 Defense (and no food)! He used his TP ability for almost 300 HP multiple times. Built TP on the goblins before the battle and got Penta Thrust off twice in the battle for 1000+ hp each time. The last Penta was a lifesaver.`

**Comment by soapytoast** [comment]
we should verify if this was checked in the NM audit from crit on ASB.

**Comment by austinclprojects** [comment]
https://github.com/TabulaRasaXI/TabulaRasa/pull/245
