### ISSUE TITLE
🐛 Guivre Pathing

### ISSUE THREAD

**Issue by Simseru** [TabulaRasaXI/TabulaRasa#158]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce
Guivre in kuftal doesn't do his typical roam path. He just sits down in the big room and roams a radius like a normal mob.

**Comment by bran-van-d** [comment]
This has been adjusted -- I am not sure where this was fixed, but I was recently in Kuftal and saw him pathing as expected.
