### ISSUE TITLE
Monks feel like guard is not working correctly 

### ISSUE THREAD

**Issue by twelvedudes** [TabulaRasaXI/TabulaRasa#162]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

Monks in the “questions “ part of tabula are discussing how they feel guard is not working

**Comment by xammy0** [comment]
It feels like when guarding above level 10 or so you begin taking more damage than a normal attack from the mob. It happens consistently.

**Comment by neosatus** [comment]
Confirmed that Guard is not working, ASB devs are looking into the fix.

**Comment by soapytoast** [comment]
https://github.com/TabulaRasaXI/TabulaRasa/issues/162

**Comment by xammy0** [comment]
MNKs are still taking too much damage when guarding after the update from today. I continue to take more damage from guarded hits than from regular hits, it is definitely not calculating the damage correctly. It appears that guarding is working correctly for monsters and they are now guarding against weapon skills.

**Comment by xammy0** [comment]
After further testing it appears that guard is lowering the damage received occasionally, but the majority of the time MNKs are still receiving more than an average damage per hit.

**Comment by xammy0** [comment]
After playing for another 9 days, I can 100% confirm that Guard is not working properly for players. I take MORE damage when guarding against level 60 mobs. It's actually become a problem at this point

**Comment by austinclprojects** [comment]
There is a bit of work that's needed on the damage formula but also guard animations aren't lining up with actual guards.

**Comment by bran-van-d** [comment]
There have been a variety of PRs related to guard. Will close this for now until we get reports otherwise. Ill check in with our resident MNK as well. 

https://github.com/AirSkyBoat/AirSkyBoat/pull/249
https://github.com/AirSkyBoat/AirSkyBoat/pull/274
https://github.com/AirSkyBoat/AirSkyBoat/pull/1484
