### ISSUE TITLE
🐛 Assassin Trait Missing

### ISSUE THREAD

**Issue by Simseru** [TabulaRasaXI/TabulaRasa#165]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce
Thief is missing the assassin trait at 60. Feelsrealbadman
![THFTraits](https://user-images.githubusercontent.com/59345270/181137267-b9bb77f4-23d7-4520-9694-613f82cec8a5.PNG)

**Comment by Simseru** [comment]
Not just a display issue either, TA dmg was the normal small bonus, no super crit when behind target, just some extra bonus dmg.

**Comment by soapytoast** [comment]
https://github.com/TabulaRasaXI/TabulaRasa/blob/staging/sql/traits.sql
it is a CoP trait and is content locked
