### ISSUE TITLE
🐛 Avatar's Favor is Active

### ISSUE THREAD

**Issue by Simseru** [TabulaRasaXI/TabulaRasa#166]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce
Avatars Favor ability is active and useable currently.

**Comment by soapytoast** [comment]
issue found and corrected. Will reflect change next time the clusters restart. 
https://github.com/AirSkyBoat/AirSkyBoat/pull/232
