### ISSUE TITLE
🐛 Roc/Simurgh

### ISSUE THREAD

**Issue by Simseru** [TabulaRasaXI/TabulaRasa#167]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce
This was already reported and looks like it was closed.
Roc and Simurgh both still lack 2hr and draw in mechanics.

Seem under tuned as well.

**Comment by neosatus** [comment]
Confirmed fixed post patch. Can be closed. @soapytoast
