### ISSUE TITLE
🐛 displayed mp costs are not correct

### ISSUE THREAD

**Issue by twelvedudes** [TabulaRasaXI/TabulaRasa#168]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

spell costs are wrong

![image](https://user-images.githubusercontent.com/108678300/181145606-c355d7e3-3a41-4b69-acca-ec2ab6acfd3d.png)

spells are shown at cost

**Comment by soapytoast** [comment]
This is a limitation of the client, there are .dat files you can get from here https://github.com/Era-Lusiphur/FFXI-DATs to correct this.
