### ISSUE TITLE
Mjoll is selling OOE stuff

### ISSUE THREAD

**Issue by ffxiWaxer** [TabulaRasaXI/TabulaRasa#17]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x ] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [xx ]x I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

Mjoll is selling out of era ammo and other shit. Mithril Bolts can be bought for 2k a stack atm. 

https://ffxiclopedia.fandom.com/wiki/Mjoll?oldid=134181 2006

**Comment by Warp-ass** [comment]
https://github.com/TabulaRasaXI/TabulaRasa/pull/29
