### ISSUE TITLE
🐛 Freesword's Staff being sold when Windy isn't 1st. It's also vendoring for way more than it should. 

### ISSUE THREAD

**Issue by asha-bellanar** [TabulaRasaXI/TabulaRasa#170]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Go to any Windy guard, buy Freesword's staff, vendor staff for 1400 gil. 

## Expected behavior
It should only be sold when Windurst is in 1st place, and I don't think 1400 gil is the correct amount. 
https://ffxiclopedia.fandom.com/wiki/Windurst_Conquest_Points_Items?direction=prev&oldid=23728

**Comment by neosatus** [comment]
It should be always sold however the sell price was wrong. Fixed in ASB, can be closed.
