### ISSUE TITLE
🐛 Desynthesis Overtuned

### ISSUE THREAD

**Issue by MeyiLekoh** [TabulaRasaXI/TabulaRasa#174]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

Desynthesis is supposed to have a very low success rate, but a very high HQ rate. While desynthesizing Cornettes, I noticed the success rate was abnormally high, and I only HQed once out of a few dozen attempts. The ratios of breaking/success/HQ feels more like a regular synthesis.

Edit: I have no desynthesis moghouse enhancements at this time.

## Steps to reproduce

1. Get some lightning crystals and Goldsmithing skill to about 10 (Cornettes are 14).
2. Desynth Cornettes.
3. Could probably desynth anything honestly, this is just what I used.

## Expected behavior

1. High failure/break rate.
2. Low success rate.
3. High HQ rate on successes.

![Desynthesis](https://user-images.githubusercontent.com/47701928/182261890-0d5d9856-e4e7-4c88-85c3-2761b603fb88.png)

**Comment by bran-van-d** [comment]
Fixed by https://github.com/AirSkyBoat/AirSkyBoat/pull/584 and https://github.com/AirSkyBoat/AirSkyBoat/pull/381
