### ISSUE TITLE
Climbpix Highrise and Gambilox Wanderling dont use 2hours

### ISSUE THREAD

**Issue by hititncritit** [TabulaRasaXI/TabulaRasa#175]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [ ] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`
Climbpix Highrise and Gambilox Wanderling dont use 2hours, might be undertuned also.
At lv 59 THF/nin capped dagger, high evasion I solod  Highrise with 50% hp remaining and Gambilox with 95% remeaining.

**Comment by austinclprojects** [comment]
https://github.com/TabulaRasaXI/TabulaRasa/pull/251
