### ISSUE TITLE
Assassin perk not working fully

### ISSUE THREAD

**Issue by hititncritit** [TabulaRasaXI/TabulaRasa#176]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [ ] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

The assassin perk for lv 60 thf should guarantee a crit on trick attack but it never crits.
It does seem to ensure a hit though.

**Comment by neosatus** [comment]
Assassin trait should be disabled as it's a COP locked trait. Is it in your list?

EDIT: I just hit 60 on my THF and Assassin is not in my trait list, this ticket can be closed @soapytoast
