### ISSUE TITLE
🐛 Mobs turning while asleep  from bolts

### ISSUE THREAD

**Issue by hititncritit** [TabulaRasaXI/TabulaRasa#178]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [ ] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

A couple of undead mobs turn while asleep from sleep bolts when I go behind to sneak attack them. Just one turn each, so im able to keep circling and get my attack off.

**Comment by bran-van-d** [comment]
Undead mobs should not be sleep-able, which was fixed in ASB here: https://github.com/AirSkyBoat/AirSkyBoat/pull/2069

Their turning was perhaps related to that inconsistency.
