### ISSUE TITLE
Smn Pep Cost

### ISSUE THREAD

**Issue by Kerm3** [TabulaRasaXI/TabulaRasa#18]
Look into pep costs for spirits (Carbuncle is good) 

Currently lvl 25 is costing 1 MP w/ Auto Refresh 
1~18: 1 MP/3 seconds
19~24: 2 MP/3 seconds
25~37: 2 (1) MP/3 seconds
38~56: 3 (2) MP/3 seconds
57~74: 4 (3) MP/3 seconds
75~80: 5 (4) MP/3 seconds
81~89: 6 (5) MP/3 seconds
90: 6 (4) MP/3 seconds
91~99: 7 (5) MP/3 seconds

^ Current Retail
_____
V 2005-2006

1-4 | 2 mp/tick
-- | --
5-8 | 3 mp/tick
9-13 | 4 mp/tick
14-17 | 5 mp/tick
18-22 | 6 mp/tick
23-26 | 7 mp/tick
27-31 | 8 mp/tick
32-35 | 9 mp/tick
36-39 | 10 mp/tick
40-46 | 11 mp/tick
47-48 | 12 mp/tick
49-53 | 13 mp/tick
54-57 | 14 mp/tick
58-62 | 15 mp/tick
63-66 | 16 mp/tick
67-71 | 17 mp/tick
72-75 | 18 mp/tick
https://ffxiclopedia.fandom.com/wiki/Fire_Spirit?oldid=112261

</body>
</html>

**Comment by 0phie** [comment]
I audited these for AirSkyBoat and based on 2010 values everything was correct besides elementals. TR staff will have to make a decision if they want to modify to '05/'06 values as in many cases they said they weren't explicitly locking the core functions of the server to those dates, rather just 75 era as a whole. 

https://github.com/AirSkyBoat/AirSkyBoat/pull/76
