### ISSUE TITLE
Overtuned NM: Huu Xalmo The Savage

### ISSUE THREAD

**Issue by xammy0** [TabulaRasaXI/TabulaRasa#182]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Popped Huu Xalmo The Savage with MNK59/NIN28, WAR60/NIN30, RDM60/THF30 and the NM was definitely overtuned. Has way too much HP and hits like a truck. We slept him and warped out, would have died before he hit 90% hp.

**Comment by austinclprojects** [comment]
Looking at FFXIclopedia history, this NM doesn't seem like a pushover. HP and level are correct in database.
