### ISSUE TITLE
🐛 <Replace this with Bug Summary>

### ISSUE THREAD

**Issue by Blackwingedicey** [TabulaRasaXI/TabulaRasa#191]
Chocobo digging is messed up. I zoned into an Yhoator Jungle, after not digging for over 24 hours.  i was able to dig once, and then it gives me the "you must wait longer to preform that action" no matter what i do. I have zoned, i have waited for over 5 mins and tried again. I have changed my chocobo and still have issue.

**Comment by MeyiLekoh** [comment]
Really botched the formatting, but yes, I've been hearing from multiple LS mates that digging is broken and only allows one item per day. This happened after the Tuesday update.

Edit: So I was able to dig up more than one item by running around. However, after 18 digs, I was no longer allowed to dig. :/

**Comment by bran-van-d** [comment]
Digging has received an update. While there might be other issues related to it, we will report them separately as ASB is currently undergoing a lot of changes.
