### ISSUE TITLE
🐛 Missing weapon skill Energy steal

### ISSUE THREAD

**Issue by hititncritit** [TabulaRasaXI/TabulaRasa#192]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [ ] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

After a recent update the dagger skill energy steal is missing.

**Comment by MeyiLekoh** [comment]
I'd like to add RDM is reporting missing Red Lotus Blade and Seraph Blade.

**Comment by panicstevenson** [comment]
> I'd like to add RDM is reporting missing Red Lotus Blade and Seraph Blade.

Judging from [this thread](https://forum.square-enix.com/ffxi/threads/25474-Red-Lotus-Blade-Seraph-Blade-Seraph-Strike?p=338318&viewfull=1#post338318) looks like they weren't available in era.

**Comment by bran-van-d** [comment]
Fixed by https://github.com/AirSkyBoat/AirSkyBoat/pull/486
