### ISSUE TITLE
🐛 Bolt Additional Effect proc rate low

### ISSUE THREAD

**Issue by Glenevere** [TabulaRasaXI/TabulaRasa#194]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Use an additional effect bolt against enemy (Blind/Acid bolts)

Proc rate appears to be between 5-7%

## Expected behavior

Proc rate should be much higher, 70-80% unless fighting much stronger enemies @75

**Comment by neosatus** [comment]
Blind and Acid bolt both only have a 10% proc rate in the code and I can't find any reference on FFXIclopedia showing they should be higher. Need source.

**Comment by MeyiLekoh** [comment]
Two comments from FFXI Allakhazam suggest very high proc rate. One said 90-95%, the other said they notice it typically procs so long as they don't miss.

https://ffxi.allakhazam.com/db/item.html?fitem=3011

Anecdotal, but sometimes that's all we have. :/ 

Also this is from Nasomi. Another private server, so YMMV, and I don't know how much we care what other servers do. But they're claiming 70% proc rate for IT/exp monsters.

https://na.nasomi.com/forum/viewtopic.php?t=6415

Sorry I can't seem to find more than that. We may need retail testing.

**Comment by austinclprojects** [comment]
Fixed last update
