### ISSUE TITLE
🐛 SMN AF quest blocked by Aspir quest

### ISSUE THREAD

**Issue by Glenevere** [TabulaRasaXI/TabulaRasa#198]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

SMN AF quest "Class Reunion" appears to be being blocked by Aspir quest. No note of this being an issue on wiki sites for quest

https://ffxiclopedia.fandom.com/wiki/Class_Reunion

https://ffxiclopedia.fandom.com/wiki/Making_the_Grade

**Comment by bran-van-d** [comment]
Closing this out as it is quite common for quests to block other quests if they are picked up and not completed.
