### ISSUE TITLE
🐛 Bastok Mission 3-1 not progressing

### ISSUE THREAD

**Issue by Glenevere** [TabulaRasaXI/TabulaRasa#199]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Bastok Mission 3-1 The Four Musketeers
https://ffxiclopedia.fandom.com/wiki/The_Four_Musketeers

Accept mission, speak with Iron Eater twice, zone into Beadeaux for cutscene.

From this point onward you will not be able to progress. Possible that kills aren't counting towards progress OR cutscenes on leaving Beadeaux are broken.
If you leave Beadeaux with too few kills, no cutscene, if you leave after achieving 20+ kills, still no cutscene.

## Expected behavior

If you have too few kills you will receive a cutscene when leaving Beadeaux saying that you need to kill more. If you have enough you will receive the mission successful cutscene.

**Comment by bran-van-d** [comment]
I feel like Glenevere's thought that it may not be counting kills is accurate. [This section in the mission code](https://github.com/TabulaRasaXI/TabulaRasa/blob/staging/scripts/missions/bastok/3_1_The_Four_Musketeers.lua#L169-L179) says that if you have **more than 1 kill** or **less than 22**, receive the cutscene about needing to kill more mobs. This makes me believe that our kill count is being stuck at 0, as me and several other players all report the same behaviour.

[The block for managing the kill counts is here](https://github.com/TabulaRasaXI/TabulaRasa/blob/staging/scripts/missions/bastok/3_1_The_Four_Musketeers.lua#L137-L148). To be clear this file was not updated in the recent release, so it is likely one of the imported scripts may have had a change preventing this block from functioning.

**Comment by bran-van-d** [comment]
Fixed by https://github.com/TabulaRasaXI/TabulaRasa/pull/219
