### ISSUE TITLE
🐛 Airships not completing trip.

### ISSUE THREAD

**Issue by Glenevere** [TabulaRasaXI/TabulaRasa#201]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Take Airship to any location. You will zone into airship from Destination A. 
Airship will blackscreen at the end of the flight and not deposit you to Destination B. 
You will be stuck like this indefinitely.

If you log out / log on you will be on the same flight but going back to Destination A where the same will happen.

## Expected behavior

Airship completes flight and deposits you to Destination B

**Comment by bran-van-d** [comment]
Fixed by https://github.com/TabulaRasaXI/TabulaRasa/pull/219
