### ISSUE TITLE
🐛 Auction house giving false sell notifcation

### ISSUE THREAD

**Issue by Glenevere** [TabulaRasaXI/TabulaRasa#202]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Put item up for sale, another player buys item, sold notification goes to wrong player.
Players are confirming this by taking all of their items successfully off their listings and having no gil received in delivery box. 

Only the notification is at fault here. The auction house is working as intended. 

My guess is that the seller and notification recipient have listed the item at the same amount. Notification pulling wrong info due to this.

## Expected behavior

When an item sells the seller should be the one getting notifcation, not another person who listed the same item.

**Comment by MeyiLekoh** [comment]
Adding that this is still broken as of today. It told me I sold five beastcoins to Hit, when I only sold him two. I was confused why the gil was missing from my delivery box.

![Missing Delivery Box Gil3](https://user-images.githubusercontent.com/47701928/187588909-acce4122-3e95-4d1c-ba02-9d92f15d3ef1.png)

![Missing Delivery Box Gil2](https://user-images.githubusercontent.com/47701928/187588967-1237f2b4-a119-4a51-8c60-6c6e7b263af2.png)

![Missing Delivery Box Gil](https://user-images.githubusercontent.com/47701928/187588928-b859030f-994a-4d65-bcfc-905084c84060.png)
