### ISSUE TITLE
🐛 Missing mobs from some zones (Castle Oztroja)

### ISSUE THREAD

**Issue by Glenevere** [TabulaRasaXI/TabulaRasa#203]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Castle Oztroja top floor is missing mobs from southern 2 lamp rooms. Some in-game reports from players make me suspect there are others missing. Bo'Who Warmonger and cohorts being some of them

## Expected behavior

There should be more Yagudo in these rooms around the torch

**Comment by neosatus** [comment]
The missing mobs is due to the code they added to reduce the number of beastmen in dungeons. That should not affect NMs however.
