### ISSUE TITLE
Mob drops- Davoi Fire Belchers

### ISSUE THREAD

**Issue by Gordge** [TabulaRasaXI/TabulaRasa#205]
- [x] Killed about 10 fire belchers and have had 0 drops, under TH1 , xammy whos has TH2 also had the same results.
- [ x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x ] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

Davoi Fire belchers drops disabled?

**Comment by austinclprojects** [comment]
Not sure if this is old, but they have drops.
