### ISSUE TITLE
Quest: Gourmet

### ISSUE THREAD

**Issue by xammy0** [TabulaRasaXI/TabulaRasa#206]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

When attempting the quest Gourmet, the NPC Salimah initially gives you the quest, but when trading a Treant Bulb nothing happens. Speaking to her any time after the quest appears in your log results in the dialog "Thanks to you, I'll make the best dish yet!". She says this every time and does not accept any trades from me,

## Expected behavior

The NPC Salimah should accept one of the 3 items, and provide a line of dialogue and reward depending on the item traded.

**Comment by austinclprojects** [comment]
This was due to zone bug, works now.
