### ISSUE TITLE
🐛 NM Mimas not spawning in Upper Delkfutt's Tower

### ISSUE THREAD

**Issue by Glenevere** [TabulaRasaXI/TabulaRasa#208]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

NM Mimas not spawning. 
https://github.com/TabulaRasaXI/TabulaRasa/blob/staging/scripts/zones/Upper_Delkfutts_Tower/mobs/Mimas.lua

## Expected behavior

Supposed to respawn every 15-20mins

**Comment by austinclprojects** [comment]
https://github.com/TabulaRasaXI/TabulaRasa/pull/244
