### ISSUE TITLE
🐛 Dark Puppet zone in not triggering cutscene

### ISSUE THREAD

**Issue by Glenevere** [TabulaRasaXI/TabulaRasa#209]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Be DRK 50+ and eligible for quest (af1 completed)
Talk to Cid
Obtain Darksteel Ingot
Zone into Ordelle's Caves to receive cutscene with Zeid. However cutscene doesn't  trigger

## Expected behavior

Cutscene triggers to allow you to progress quest

**Comment by austinclprojects** [comment]
Assuming this was fixed with zonein
