### ISSUE TITLE
🐛 Hitting the Marquisite not progressing

### ISSUE THREAD

**Issue by Glenevere** [TabulaRasaXI/TabulaRasa#210]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Be THF 50+ and eligible for quest (af1+af2 completed)
Speak with Nanaa Mihgo + acquire Key Item
Speak with Yatniel, then trade him 4 Quake Grenades
Yatniel doesnt accept the items however and gives strange dialogue error (see image)

![Notaro_2022 08 14_172226c](https://user-images.githubusercontent.com/109822033/185266894-5a10fea3-8a5b-437b-ae04-a6da9c3ab259.png)

## Expected behavior

Yatniel should request the grenades in dialogue and then accept the trade

**Comment by MeyiLekoh** [comment]
Can confirm this is still broken.

**Comment by austinclprojects** [comment]
https://github.com/TabulaRasaXI/TabulaRasa/pull/239
