### ISSUE TITLE
🐛 Addition effect: Elemental Damage on weapons not proccing 

### ISSUE THREAD

**Issue by Glenevere** [TabulaRasaXI/TabulaRasa#212]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Many/most/all weapons with the "Additional Effect: Elemental damage" line don't appear to be proccing ever.

I have noticed that the weapon Nadrs Additional effect: Poison procs quite often which is era accurate so believe this is only regarding the elemental damage weapons. Had multiple reports regarding this

## Expected behavior

Addition Effect: Elemental Damage proc rate was fairly low 5-10% but you still would have seen it

**Comment by austinclprojects** [comment]
Looks like most are set to a 5% proc rate, but they do proc.
