### ISSUE TITLE
🐛 Blade of Darkness quest not progressing

### ISSUE THREAD

**Issue by Glenevere** [TabulaRasaXI/TabulaRasa#215]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Blade of Darkness quest not flagging from zoning from Palborough Mines to Zeruhn Mines cutscene.
If player is already on quest and zoning into Beaudeaux after achieving 100 kills, the cutscene to complete quest on zone in isn't activating either.

## Expected behavior

Cutscenes should be triggering from both zone ins

**Comment by austinclprojects** [comment]
@Glenevere Was this an issue related to the zone in bug? Is it fixed now?

**Comment by neosatus** [comment]
@austinclprojects It was and should be. Maybe a GM can verify?

**Comment by austinclprojects** [comment]
Yep, works now.
