### ISSUE TITLE
🐛 NM Zi'Ghi Boneeater spawning like normal mob

### ISSUE THREAD

**Issue by Glenevere** [TabulaRasaXI/TabulaRasa#216]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

NM Zi'Ghi Boneeater is just respawning after every kill instead of chance of spawn instead of placeholder. 

## Expected behavior

Should be random chance of spawning instead of the Veteran Quadav in his spawn room

**Comment by austinclprojects** [comment]
Just checked and the NM isn't up, maybe this was a transient issue?
