### ISSUE TITLE
🐛 Serket Spawn

### ISSUE THREAD

**Issue by Simseru** [TabulaRasaXI/TabulaRasa#22]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce
Serket is currently spawning in the new retail smaller room instead of the original larger room.

**Comment by Warp-ass** [comment]
https://github.com/TabulaRasaXI/TabulaRasa/pull/31

**Comment by bran-van-d** [comment]
cc @austinclprojects  This issue will be fixed in a to-be-merged ASB PR: https://github.com/AirSkyBoat/AirSkyBoat/pull/1818
