### ISSUE TITLE
Dark Elemental Stuck 

### ISSUE THREAD

**Issue by xammy0** [TabulaRasaXI/TabulaRasa#220]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Dark Elemental in the corner of G-8 appears to be stuck in the ground and inaccessible.

## Expected behavior

Dark Elemental should be floating around normally in the corner of G-8

**Comment by austinclprojects** [comment]
@xammy0 What zone?

**Comment by bran-van-d** [comment]
Closing as this was likely an unlucky happenstance.
