### ISSUE TITLE
🐛 Digging Consumes Two Greens

### ISSUE THREAD

**Issue by MeyiLekoh** [TabulaRasaXI/TabulaRasa#222]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

Currently digging is taking two greens per dig attempt.

## Steps to reproduce

1. Buy at least two greens from NPC.
2. Dig.

## Expected behavior

Consume one green per dig attempt.

![DoubleDig1](https://user-images.githubusercontent.com/47701928/186042409-afc38eb6-fb96-4079-a4de-cc703e95b511.png)

![DoubleDig2](https://user-images.githubusercontent.com/47701928/186042437-dc3826c3-3dbd-416e-92a3-01632dee3ea4.png)

**Comment by austinclprojects** [comment]
https://github.com/TabulaRasaXI/TabulaRasa/pull/243
