### ISSUE TITLE
🐛 DRG Spirit Link sometimes gives TP

### ISSUE THREAD

**Issue by MeyiLekoh** [TabulaRasaXI/TabulaRasa#227]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

Dragoon's Spirit Link sometimes gives the dragoon the wyvern's TP. This is technically OoE for this time, as it was added in around June 2010 according to wiki. I didn't see it added to any previous entries.

https://ffxiclopedia.fandom.com/wiki/Spirit_Link?oldid=1137058

## Steps to reproduce

1. Fight some monsters as DRG main.
2. Use Spirit Link after a few hits.
3. Should receive partial wyvern's TP.

## Expected behavior

Spirit Link should just give the wyvern HP, not the owner TP at this time.

**Comment by bran-van-d** [comment]
Fixed by ASB: https://github.com/AirSkyBoat/AirSkyBoat/pull/1596
