### ISSUE TITLE
🐛 Silence Gas overpowered

### ISSUE THREAD

**Issue by MeyiLekoh** [TabulaRasaXI/TabulaRasa#229]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

Silence Gas shouldn't almost one shot a player, and I suspect some other monster moves are a little overpowered (maybe from the magic acc boost?). I was fighting a level 62 funguar in The Boyahda Tree as a level 60, and it did 724 damage to me.

## Steps to reproduce

1. Fight a tough funguar until he TP.
2. Have Protectra and Shellra on. (Don't know if Shellra helps, but it is affected by magic acc and magic att).

## Expected behavior

It should definitely do some good damage, but not 700+... especially with a 2 level difference.

![SilenceGas](https://user-images.githubusercontent.com/47701928/186588818-55adb928-23c6-46e7-ae48-9100f5a6730c.png)

**Comment by austinclprojects** [comment]
Dark Spore and Silence Gas are both Breath type attacks meaning they can really fuck you up at high health. The numbers LGTM.
