### ISSUE TITLE
🐛 Not awarded titles on mob death

### ISSUE THREAD

**Issue by Simseru** [TabulaRasaXI/TabulaRasa#23]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce
We killed skewer sam today and did not get the title for killing him. An avatar landed the defeating blow so its probably related to if a pet lands the killing blow it doesn't know how to check for the pet owner to assign the title to that group of players.

**Comment by mumencoder** [comment]
Fixed by https://github.com/LandSandBoat/server/pull/2459
