### ISSUE TITLE
🐛 Invisible Characters

### ISSUE THREAD

**Issue by Simseru** [TabulaRasaXI/TabulaRasa#24]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce
When a character approaches you from 50+ yalms they are invisible unless you move your character and force a packet update from the server.

**Comment by The-Aerec** [comment]
This is an LSB issue. Lets push this up to them.

**Comment by soapytoast** [comment]
Aerec has created LSB issue here https://github.com/LandSandBoat/server/issues/2228

**Comment by mumencoder** [comment]
Fixed by https://github.com/LandSandBoat/server/pull/2248
