### ISSUE TITLE
RNG AF3 Fight Ice arrows after

### ISSUE THREAD

**Issue by Blackwingedicey** [TabulaRasaXI/TabulaRasa#248]
go to [Xarcabard] where you see a cutscene. Go to the cave in E-7 and examine the ???. A cutscene starts where a NM tiger called [Koenigstiger] starts attacking you. When the cutscene ends, kill Koenigstiger.

Once the tiger is dead, go to the cave at E-8 and examine the ??? for another cutscene. After that cutscene, examine the ??? at E-8 again to get a bonus prize of 99 ice arrows.

I did this, I did NOT get a stack of arrows, I just got one. lmao.

**Comment by austinclprojects** [comment]
https://github.com/TabulaRasaXI/TabulaRasa/pull/252
