### ISSUE TITLE
Sidewinder Issue

### ISSUE THREAD

**Issue by Blackwingedicey** [TabulaRasaXI/TabulaRasa#255]
Was told to make a issue report for this.  Having issues with Sidewinder and the amount of misses it does. I have played Ranger on retail, and other privte servers and never missed as much as I do here, and I have better gear here . Normal miss ratio is 15-25% depending on gear, I am on average missing sidewinder standing at proper distances of 8.3-10 (best is 8.5 and 9.6 for damage) as well as 12.3 (I almost never use)

The stats of Sidewinder need to be looked at. I know its inaccurate as hell, but with 71+10 agi, and 193 skill and 51 + racc in gear. I should not be hitting 1/15 sidewinders.
Rise — 08/23/2022
Thanks Icey, that is unfortunate. Sidewinder is one of my favorite weapon skills in the game (such fond memories of melting things with it). We'll take a look
Icey — 08/23/2022
If you leave this ticket open, and give me situations or things i can do to help, i will do so.
Icey — 08/23/2022
I just had a revaluation that may be of help. I was talking with notaro about this and we wonder if the ranged weaponskills are not taking gear into effect, which would cause the issues. We do not believe that ranged acc, or the gear is not working properly on normal ranged attacks. And the damage seems correct. but the weaponskills have not seemed correct since the last major patch on 7/8. However was not noticeable due to standing in correct position and having better gear. If someone had no gear on and using the lower lvl weapon skills I believe this point would be proven. That being said with having sidewinder at 55 and huge amount of gear and stats to support it, it kinda proves that that may be the case. Again anything I can do to help support this, please do not be afarid to  ask, I am last mainjob active ranger left that we know of and i do often have free time to test things.
Icey — 09/06/2022
Sidewinder has not improved with this latest update.  Still believe somehow the WS is not taking gear into effect somehow.
Rise — 09/06/2022
Sorry haven't gotten around to this quite yet but thanks for keeping it in the loop
I can't imagine Sidewinder has omissions for gear stats applying to its accuracy, but we shall see!
Icey — 09/06/2022
I honestly can’t think of anything else. Honestly my barrages are almost always  full barrages and I have from my experience playing on both retail and other private servers, it is way off. Normally I’d be missing 15-20%  of sidewinders and in this case I’m missing 90-95%
Icey — Yesterday at 5:54 PM
was something adjusted for /ra this last update?
oldoldman — Yesterday at 6:50 PM
No, I haven't looked at this yet
make a github issue for this if you can plz
Icey — Yesterday at 10:41 PM
Ok Sorry only reason i asked is oddly now im haveing huge barrage issues.
oldoldman — Yesterday at 11:11 PM
nothing wit hranged attacks has been touched recently

**Comment by bran-van-d** [comment]
Ranged Acc was buffed. can reopen if it still feels bad!
