### ISSUE TITLE
🐛 Prime Avatar Fights without Forks

### ISSUE THREAD

**Issue by MeyiLekoh** [TabulaRasaXI/TabulaRasa#258]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

Like on the Era server, players are allowed to enter a prime avatar fight without a tuning fork in their temporary key items so long as someone else in the party has one.  

## Steps to reproduce

1. Have someone else in party grab a tuning fork to one of the prime avatar fights.
2. Go to the prime avatar cloister.
3. Have party member enter with tuning fork.
4. Enter without having the tuning fork on you.

## Expected behavior

Everyone who wants to fight the avatar should have the tuning fork on them.

https://ffxiclopedia.fandom.com/wiki/Trial_by_Fire

"Everyone who is involved in the fight must have a tuning fork of the correct protocrystal."

**Comment by MeyiLekoh** [comment]
ADDITIONAL INFORMATION:
- Apparently failing a prime fight doesn't wipe the fork. I didn't try entering a second time (because I assumed the tuning fork would be wiped).

**Comment by chocoboturd** [comment]
Also noting that entering the battlefield without the fork also GIVES the player the fork. I have the tuning fork in my key items still. (This is Embrace, lmk if you want to remove the fork my from my KI since it's erroneously granted to me!)

**Comment by bran-van-d** [comment]
This check was added here: https://github.com/AirSkyBoat/AirSkyBoat/pull/626/files
