### ISSUE TITLE
Hatchet break rate

### ISSUE THREAD

**Issue by xammy0** [TabulaRasaXI/TabulaRasa#259]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Steps to reproduce

Hatchets break constantly.

## Expected behavior
Can someone please test and confirm the break rate is correct? Logging is not feasible at this time due to hatchet breaks being so expensive.

**Comment by austinclprojects** [comment]
Hatchet has same break rate as pickaxe and sickle. Field gear reduces break rates pretty dramatically.

**Comment by xammy0** [comment]
Can you check if Field Gear is working correctly then?

**Comment by neosatus** [comment]
It 100% is, source me and lots of mining.

**Comment by xammy0** [comment]
> It 100% is, source me and lots of mining.

Do hatchets and field gear use the same code as pickaxes?

**Comment by neosatus** [comment]
Yes it does. The effect on mining was very noticible. Everything looks good
so if it's not working then it's an obscure bug.
