### ISSUE TITLE
🐛 Korroloka Tunnel Jelly Slime Oil Drop Rate Low

### ISSUE THREAD

**Issue by MeyiLekoh** [TabulaRasaXI/TabulaRasa#271]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

Currently Jelly in Korroloka Tunnel have a low drop rate. According to the wiki, they should have about a 43% drop rate, and drop up to 3x slime oils per Jelly. I remember farming these on retail in era and having a decent drop rate, often seeing two, rarely seeing three.

In the database, they are coded as:

Drop 1: 5%
Drop 2: 5%
Drop 3: 5%

With TH2, that brings them up to about 7% each.

![Jelly_DropRate](https://user-images.githubusercontent.com/47701928/192116200-25475c9a-e56d-4e42-8e5f-8b5d3e4701c6.png)

After farming 213 Jellies, I got a total of 50 slime oils. I had two monsters drop 2, and one monster drop 3.

![Jelly_DropRate2](https://user-images.githubusercontent.com/47701928/192116425-be53c67d-28c1-4894-a646-58c4ede6eee9.png)

If it was closer to wiki drop rates, it might look something like 90 oils for 213.

![Jelly_DropRate3](https://user-images.githubusercontent.com/47701928/192116467-7bbd30f5-4a1a-4880-a778-e18ebebff7d5.png)

https://ffxiclopedia.fandom.com/wiki/Jelly

I don't know how to calculate the numbers, but I suspect if we increased at least the first and maybe second drop items to Uncommon instead of Rare, it might get closer to retail era accurate. So for example, with TH2:

Drop 1: Uncommon (10% -> 15%) 
Drop 2: Uncommon (10% -> 15%)
Drop 3: Rare (5% -> 7%)

If percentages are additive, this would give ~37%, which is still shy of the 43%, but would give room for TH4 to increase up to the observed amount. (TH4 gives Uncommon 18% and Rare 8%, which would be 44%; very close to the 43% observed on wiki.)

## Steps to reproduce

1. Farm a bunch of Jellies in Korroloka Tunnel.
2. Be sad when they mostly don't drop, and rarely drop multiples. :(

## Expected behavior

Jellies should have a 43%ish drop rate of slime oils, with common drops of 2-3 multiples.

**Comment by austinclprojects** [comment]
New drop table increased drop rate that brings it pretty close to in line with what is on the wiki.
