### ISSUE TITLE
🐛 "Mom, the Adventurer?" repeat quest does not start

### ISSUE THREAD

**Issue by ProtonData** [TabulaRasaXI/TabulaRasa#28]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

This quest does not start:
https://ffxiclopedia.fandom.com/wiki/Mom,_the_Adventurer%3F?oldid=46086

and it skips to the next quest in the chain (this quest works):
https://ffxiclopedia.fandom.com/wiki/The_Signpost_Marks_the_Spot?oldid=43813

## Expected behavior

https://ffxiclopedia.fandom.com/wiki/Mom,_the_Adventurer%3F?oldid=46086
should start first, be repeatable, and unlock the next quest

https://ffxi.allakhazam.com/db/quests.html?fquest=155&p=2#m106827006566303

**Comment by mumencoder** [comment]
The expected behavior worked for me. If the 'signpost marks the spot' quest started for you, you may have hit fame 2 already and the previous quest is no longer repeatable.
