### ISSUE TITLE
🐛 Wild Card quest not progressing

### ISSUE THREAD

**Issue by asha-bellanar** [TabulaRasaXI/TabulaRasa#294]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

https://ffxiclopedia.fandom.com/wiki/Wild_Card_(Quest)

House of the Hero is not giving any cutscene, so opening the coffer is not producing the card.  Have spoken to all of the NPCs multiple times, zoned, logged off/on, etc.

It might be missing the fix from this ASB pull https://github.com/AirSkyBoat/AirSkyBoat/pull/418

**Comment by Cyber857** [comment]
https://github.com/TabulaRasaXI/TabulaRasa/blob/staging/scripts/quests/windurst/SOB6_Wild_Card.lua

on line : 73 Prog is set to 1, but never 2,

on line : 84 It is looking for Prog = 2,

proposed solution is to change line 84 to check for prog =1 (this will catch everyone in the quest who has not completed) if you change 73 to 2, the people in the quest will be stuck.

**Comment by asha-bellanar** [comment]
This is still busted.

**Comment by asha-bellanar** [comment]
Works now. Ty!
