### ISSUE TITLE
🐛 Toraimarai Canal STILL has OoE monsters

### ISSUE THREAD

**Issue by MeyiLekoh** [TabulaRasaXI/TabulaRasa#295]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [ ] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [ ] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

Poroggos and toads all over Toraimarai Canal, map 2.

## Steps to reproduce

1. Wander SE on map 2.
2. Be thwarted by toads and poroggos. :(

## Expected behavior

They shouldn't be there.

**Comment by asha-bellanar** [comment]
Poroggo Excavators are also supposed to be non-aggressive.  So if they're gonna be in there, they should at least be that rather than true hearing aggressive. 

https://ffxiclopedia.fandom.com/wiki/Poroggo_Excavator
