### ISSUE TITLE
🐛 Incorrect Crafting subskill for Errant Houppelande

### ISSUE THREAD

**Issue by dooni-dee** [TabulaRasaXI/TabulaRasa#306]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Errant Houppelande incorrect crafting subskill 

`Errant Houppelande synthesis is telling me I'm not high enough for the recipe despite having 88+1 Clothcraft, 51 Goldsmithing, 60 Leathercraft. Upon looking at the code on https://github.com/TabulaRasaXI/TabulaRasa/blob/staging/sql/synth_recipes.sql and discussing with smarter people than myself there is a mistake on the Houppelande line where the '50' value for Goldsmithing is actually in the Smithing column.'

Line is here: INSERT INTO synth_recipes VALUES (34547,0,0,0,50,0,96,30,0,0,0,4099,4241,761,821,828,829,829,830,830,851,14380,14381,14381,14381,1,1,1,1,'Errant Houppelande');

## Steps to reproduce
1. Attempt Errant Houppelande synthesis
2. Get "Synthesis canceled. That formula is beyond your current craft skill level" error message.

## Expected behavior

1. Attempt Errant Houppelande synthesis
2. Either break or succeed

Attached are some screenshots. Thank you very much for any help.
![image](https://user-images.githubusercontent.com/113268368/199634406-78ae267c-bafd-4d8c-a403-d360795ccc7a.png)
![image](https://user-images.githubusercontent.com/113268368/199634428-d42c52a2-ec32-4e16-a7fa-c8e18c59756e.png)
![image](https://user-images.githubusercontent.com/113268368/199634478-e35e7a77-609a-4dc1-b8ac-79f85368360c.png)
![image](https://user-images.githubusercontent.com/113268368/199634494-d585b7ac-4e3c-4e82-8349-a27416475dd5.png)

**Comment by bran-van-d** [comment]
This has been fixed -- not sure which issue/PR, but we're crafting it heh.
