### ISSUE TITLE
Final Sting Takes Shadows

### ISSUE THREAD

**Issue by MeyiLekoh** [TabulaRasaXI/TabulaRasa#32]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

Final Sting currently absorbs a shadow. It should go through shadows.

## Steps to Reproduce
1. Put shadows/utsusemi up
2. Feed bee TP
3. Take Final Sting to face with shadows up

## Expected behavior

Final Sting should hit the player regardless of shadows. (I know this is current wiki information, but other era servers have also contested this. I wasn't able to easily find data supporting either way.)

https://ffxiclopedia.fandom.com/wiki/Final_Sting

**Comment by 0phie** [comment]
This has been fixed.
