### ISSUE TITLE
Linkshells Underpriced from NPCs

### ISSUE THREAD

**Issue by MeyiLekoh** [TabulaRasaXI/TabulaRasa#33]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

Linkshells cost 6k from vendors. Should cost 8k as per era prices.

## Steps to reproduce

1. Go to Ilita (Port Bastok, E-7), Paunelie (Southern San d'Oria, E-8), or Khel Pahlhama (Port Windurst, H-9) and ask for a linkshell.

## Expected behavior

Linkshells should cost 8k to make. (6-14k is current retail prices)

https://ffxiclopedia.fandom.com/wiki/Linkshell?oldid=172404

**Comment by austinclprojects** [comment]
Let's just call this one QoL.
