### ISSUE TITLE
🐛 Food buff lost upon entering BCNM

### ISSUE THREAD

**Issue by Aeshur** [TabulaRasaXI/TabulaRasa#34]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce
Eat food and then enter any BCNM/battlefield fight

## Expected behavior
To not lose the food buff

**Comment by bran-van-d** [comment]
ASB PR Fixed this issue: https://github.com/AirSkyBoat/AirSkyBoat/pull/265
