### ISSUE TITLE
🐛 Invisible Not Removed Via Items

### ISSUE THREAD

**Issue by MeyiLekoh** [TabulaRasaXI/TabulaRasa#35]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

Invisible doesn't wear when you use an item (ex. Silent Oil).

## Steps to reproduce

1. Put Invisible on.
2. Use a Silent Oil.

## Expected behavior

Invisible should wear when using an item, a job ability (excluding pet abilities, I believe), casting a spell, or firing a ranged weapon.

**Comment by 0phie** [comment]
Fixed by https://github.com/AirSkyBoat/AirSkyBoat/pull/74
