### ISSUE TITLE
Pickaxe Stacking sells for 99

### ISSUE THREAD

**Issue by brad43326** [TabulaRasaXI/TabulaRasa#53]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Go to buy pickaxes and they will sell in stacks of 99 but only allow to purchase a stack of 12

## Expected behavior

Should only sell as a stack of 12 not 99

**Comment by soapytoast** [comment]
the 99 stack is a visual thing only due to the .dat's used in the retail client. They are only stacking to 12 actually.
