### ISSUE TITLE
Treasure Chests are broken 

### ISSUE THREAD

**Issue by Hatberg** [TabulaRasaXI/TabulaRasa#67]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Use Living Tools to pick a treasure chest in Oztroja.
![image](https://user-images.githubusercontent.com/46464306/178102341-de27318b-a475-45ad-b86c-8420e97485eb.png)
No gil added, no loot added to inventory/treasure pool. Living Key is consumed.

Recent gil/Recent items before sort:
![image](https://user-images.githubusercontent.com/46464306/178102362-23d65237-2778-456e-a383-53d72eed509e.png)
![image](https://user-images.githubusercontent.com/46464306/178102374-b05ff65f-73de-40ca-aca6-d5d306ebe689.png)

## Expected behavior

Add treasure to the pool after picklocking a chest.

**Comment by Hatberg** [comment]
Same issue occurred with a Living Key on a Treasure Chest from Crawler's Nest.

**Comment by Hatberg** [comment]
Same issue occurred with an actual Oztroja Chest Key on an Oztroja Treasure Chest.

**Comment by Hatberg** [comment]
Same issue occured with an Ranperre Chest Key in King Ranperre's Tomb

**Comment by MeyiLekoh** [comment]
Oops just saw this one. Adding my results. Also broken in Delkfutt.

![Broken Treasure Chest](https://user-images.githubusercontent.com/47701928/178128389-95637172-33f2-4727-b892-323b840aa318.png)

![Broken Treasure Chest2](https://user-images.githubusercontent.com/47701928/178128394-4db8d78c-8c94-40a7-bfbc-cdb449a903e4.png)

**Comment by 0phie** [comment]
This was fixed a few days ago if one of the maintainers can close this.
