### ISSUE TITLE
🐛 Hide Broken - Doesn't Work With Sight Monsters

### ISSUE THREAD

**Issue by MeyiLekoh** [TabulaRasaXI/TabulaRasa#72]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

Using Hide as THF main should remove aggro from sight monsters as long as the player isn't engaged. It should also remove aggro some sound monsters and give a few seconds to run away or get sneak up. Currently, it does not erase any hate, including sight monsters.

## Steps to reproduce

1. Aggro sight monster.
2. Use Hide.
3. Be attacked. :(

## Expected behavior

Use Hide, lose aggro, get invisible buffer.

https://ffxiclopedia.fandom.com/wiki/Hide
![Broken Hide](https://user-images.githubusercontent.com/47701928/178120538-80b95546-2cf3-4c4e-aa01-edf8454f1e6e.png)

**Comment by Simseru** [comment]
Coeurls aggro sight but track by scent so it shouldnt work on coeurls. It should only work on Scent tracking mobs if it is raining(doubt that is coded).

I have not noticed this issue on goblins or anything that is aggro sight && track sight mobs.


https://ffxiclopedia.fandom.com/wiki/Hide
When the user has the attention of an enemy that tracks by [sight](https://ffxiclopedia.fandom.com/wiki/Sight), all [enmity](https://ffxiclopedia.fandom.com/wiki/Enmity) is erased.

Hide can be used on monsters that normally track by scent if rain weather or double snow weather are in effect. Even works on monsters that detect by sound but track by scent.

**Comment by soapytoast** [comment]
I have used hide multiple times without issue, appears it has been resolved.
