### ISSUE TITLE
Smithing recipes not working

### ISSUE THREAD

**Issue by Valbrandr** [TabulaRasaXI/TabulaRasa#80]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

smithing recipes for bronze ingot and bronze sheet are not working

## Steps to reproduce

Tried crafting with fire crystal and beastcoin x4, got message it was an invalid recipe. Tried crafting with fire crystal and bronze ingot x1 for bronze sheet, got the same message

## Expected behavior

These should be valid crafting recipes

**Comment by neosatus** [comment]
This issue was resolved at some point and is no longer present. This ticket can be closed @soapytoast.
