### ISSUE TITLE
🐛 Guilds Itemless...

### ISSUE THREAD

**Issue by MeyiLekoh** [TabulaRasaXI/TabulaRasa#85]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

Woodworking Guild (and assuming other guilds) don't have any items to buy whatsoever...

## Steps to reproduce

1. Talk to Cauzeriste or Chaupire in North San d'Oria (E-3), between 6:00-21:00, any day except Firesday.

## Expected behavior

Woodworking items available to purchase.

![Broken WW Guild](https://user-images.githubusercontent.com/47701928/178130494-a22c4b5b-43ba-4c13-b402-e130e72ea6fd.png)

**Comment by Judaine** [comment]
Guild vendors have been fixed. This was an error due to a conflicting module.
