### ISSUE TITLE
🐛 Elemental Clusters Don't Count Towards Digging Fatigue

### ISSUE THREAD

**Issue by MeyiLekoh** [TabulaRasaXI/TabulaRasa#86]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

Digging fatigue is currently set to take place after 90 successful digs for the day. However, I got 98 items before fatigue. I thought it was strange, but upon further inspection, I did get 8 Water Clusters (which could account for the +8 over fatigue).

## Steps to reproduce

1. Dig during double weather (ex double rain, "squalls").
2. You will dig elemental clusters at some point.
3. When you get "must wait longer for that action" messages after a 16+ second wait, you've reached fatigue. Count up number of items.
4. Compare Elemental Clusters amount to total. See if cluster value is the amount you are over fatigue.

## Expected behavior

Fatigue after 90 items. As far as I'm aware, clusters should count towards dig success.

Including dig results so you can confirm.

8 + 4 + 12 + 8 + 10 + 7 + 3 + 1 + 12 + 8 + 12 + 12 + 1 = 98

*Note: I had none of these digging related items prior to digging.

![98 dig 1](https://user-images.githubusercontent.com/47701928/178132117-d6bdd168-57bc-470e-a469-6ac4492112d1.png)

![98 dig 2](https://user-images.githubusercontent.com/47701928/178132121-ceb27e15-6143-4203-b5a0-d267d1b25636.png)

**Comment by Simseru** [comment]
From what I can see digging fatigue is set to 100 items in the lua not 90, so you didnt get 8 extra, you got 2 less then you should have.

This is due to ore/crystals/clusters counting even if you fail to dig them due to not meeting the full requirements. So the 2 items you did not get are either crystals/clusters you dug before the weather started// after it ended or ore's that you did not have the skill//moon//weather to receive.

**Comment by MeyiLekoh** [comment]
Strange. I only got 94 items this time. No weather, so no crystals or clusters. (Edit: Only thing between greens on first picture and lauan logs on second picture are iron arrows and discord linkshell.)

![94 dig 1](https://user-images.githubusercontent.com/47701928/178410489-dbc30e05-84db-4dd4-8e46-3fb4517c7467.png)

![94 dig 2](https://user-images.githubusercontent.com/47701928/178410493-36a3d980-50cc-443e-8839-e7db32b8b652.png)
