### ISSUE TITLE
🐛 VB damage seems high

### ISSUE THREAD

**Issue by Simseru** [TabulaRasaXI/TabulaRasa#87]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce
Viper Bite damage may be a little too high after the recent changes. AVG'd 550 VB's with just SA VB on bloodtear vs drgs avg 175 Penta's.

As far as I can recall 550 VBs would be very solid number for a SATA VB on a colibri, so this seems very high for a SA VB on a non-piercing weak target.

The average was even dragged down a bit by 2 TA VBs which were in the 400's.
![VB](https://user-images.githubusercontent.com/59345270/178153427-101be3c2-c4d4-4bbe-92e3-aff45f2fc950.PNG)

**Comment by Simseru** [comment]
![Behe](https://user-images.githubusercontent.com/59345270/178165498-73180967-d6c6-4854-9437-63f3ffc5ad66.PNG)
SA VB on Behemoth at lvl 50, tried no SA but missed cause eva vs acc.

![BatHUGE](https://user-images.githubusercontent.com/59345270/178165504-07904868-5c4b-4344-b352-2e9cfa2c92d2.PNG)
RAW VB, no SA or TA on a lvl 42 bat on my way to behemoth


VB was a useless do barely more then an auto attack WS in era unless coupled with SA/TA

**Comment by Simseru** [comment]
Screen shot provided to me to add to this for a RNG/NIN in an exp party on a VT bee.
![vbb](https://user-images.githubusercontent.com/59345270/178168766-612cc068-e966-4b87-9e36-fb56df0b45a2.jpg)

**Comment by soapytoast** [comment]
had adoulin WS setting enabled on accident, corrected.
