### ISSUE TITLE
🐛 Party ! Bug

### ISSUE THREAD

**Issue by brad43326** [TabulaRasaXI/TabulaRasa#90]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

When searching for a party and choose Seek Party you get the green ! next to your name.  After you join a party the green ! remains and doesn't go back to the pearl if you have one or just your name.

## Expected behavior

Once you accept an invite or stop seeking the green ! should go away.

**Comment by brad43326** [comment]
Also when you're seeking the button still says Seek Party instead of Stop seeking in the party menu

**Comment by mumencoder** [comment]
As far as I can see the relevant code hasn't really changed since this bug popped up. Could be a client/server compatibility issue due to the update?

**Comment by brad43326** [comment]
This was opened 3 weeks ago.  Well before the update we just had so that can’t be it.

**Comment by soapytoast** [comment]
this is one of the issues that happens with parties due to clustering.

**Comment by Cyber857** [comment]
Can people who code look at "Party.cpp" line 606. It looks like the code is in place but commented out for somereason.???

**Comment by neosatus** [comment]
It does work correctly when you're in the same zone, it's only bugged across clusters. This is not easily fixed without reworking the party/alliance system to work with clusters.
