### ISSUE TITLE
Roc does not use Benediction

### ISSUE THREAD

**Issue by Hatberg** [TabulaRasaXI/TabulaRasa#91]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Get Roc to below 60%-40% HP. Benediction should occur but does not.

## Expected behavior

Benediction once at medium HP left.

**Comment by CriticalXI** [comment]
Fixed in https://github.com/LandSandBoat/server/pull/2223 pending merge.
