### ISSUE TITLE
Simurgh does not use Mighty Strikes

### ISSUE THREAD

**Issue by Hatberg** [TabulaRasaXI/TabulaRasa#93]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Get Simurgh down to 40-60% health. He should use Mighty Strikes once per combat. Currently he does not.

## Expected behavior

Mighty Strikes should be performed at around 40-60%.

**Comment by CriticalXI** [comment]
Fixed in https://github.com/LandSandBoat/server/pull/2098, pending merge.

**Comment by grammmit** [comment]
Also might pop before 21-24hrs (2hrs or so) @CriticalXI
