### ISSUE TITLE
🐛 NM uses Mijin Gakure but doesn't die

### ISSUE THREAD

**Issue by anilanar** [TabulaRasaXI/TabulaRasa#98]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

1. Fight Zhuu Buxu the Silent
2. Wait for Mijin Gakure
3. Mob does the death animation, but then just stands up and does not die.

![2022-07-11-09-37-13](https://user-images.githubusercontent.com/753736/178213011-c8eab086-109f-4f63-84e1-0fe27e53f25f.png)

## Expected behavior

1. Mob dies after death animation

**Comment by CriticalXI** [comment]
Monsters in general do not die when using Mijin Gakure. Even noted on this specific mob's wiki page "Occasionally uses [Mijin Gakure](https://ffxiclopedia.fandom.com/wiki/Mijin_Gakure), but is not KO'd from its use."

**Comment by anilanar** [comment]
@CriticalXI Ah ok thanks.
