### ISSUE TITLE
Many Ninja Weaponskills Don't Work

### ISSUE THREAD

**Issue by vernam-k** [TabulaRasaXI/TabulaRasa#99]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce
**Update**: Elemental Weaponskills have been fixed in https://github.com/AirSkyBoat/AirSkyBoat/pull/117.
**Blade: Retsu** paralysis effect remains bugged.

<s>Use **Blade: Teki** and **Blade: To**:
The animations execute but weaponskills do nothing, no damage or even text in combat log about a miss. This may affect other weaponskills too like Blade: Chi but I haven't tested it yet.</s>

Use **Blade: Retsu**:
Example: Blade Retsu against a level 22-27 Quadav. Player was level 50 with 148 katana skill, yet paralyze instantly wears off.
![retsu](https://user-images.githubusercontent.com/109107184/178391361-e24bcd12-1bc3-401e-aefb-4122f7c8ae73.jpg)
Paralysis effect usually wears off instantly, sometimes lasts a few seconds. Rarely lasts longer.

## Expected behavior

<s>**Elemental Weaponskills**:
Should do damage.</s>

**Blade Retsu**:
![retsu](https://user-images.githubusercontent.com/109107184/178383648-12ac39b4-b32a-4016-81ba-6472a7f4285e.jpg)
I don't believe it should be affected by (magic?) resists. It's a physical damage WS with STR and DEX modifiers.
1000 TP: 30 seconds
2000 TP: 60 seconds
3000 TP: 120 seconds
Paralysis effect is fairly strong (up to ~30%?)

**Comment by 0phie** [comment]
The no damage log piece is due to the resist calculation for these weaponskills being malformed which is fixed in https://github.com/AirSkyBoat/AirSkyBoat/pull/117 .

As for the duration something is paralyzed for in the case of retsu, this is subject to the duration penalties all spells have thus if you are much lower level than the mob you will rarely get much of a duration at all. This also takes in to account both dStat and effect resistance, it is likely with the katana skill you are rolling low due to there being a steeper skill penalty for weapons compared to magic.

**Comment by vernam-k** [comment]
@OpheliaXI 
In regards to Blade: Retsu, so if I'm much _higher_ level wouldn't this behavior be a bug? The Copper Quadav in the screenshot was likely level 22-27, but I was level 50 w/ 148 katana skill. Something changed last week after the big patch because this used to work normally.

**Comment by vernam-k** [comment]
![retsu](https://user-images.githubusercontent.com/109107184/179117153-ae04ba69-05a8-4a26-bff5-c7f862489f65.jpg)

**Comment by soapytoast** [comment]
closing this one as the base issue of the WS's not doing dmg was resolved.
Resist issues are still ongoing and being worked https://github.com/TabulaRasaXI/TabulaRasa/issues/102
